import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Anta, Archivo_Black } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const anta = Anta({
  variable: "--font-anta",
  weight: "400",
  subsets: ["latin"],
});

const archivoBlack = Archivo_Black({
  variable: "--font-archivo-black",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${anta.variable} ${archivoBlack.variable} antialiased`}
      >
        <div className="absolute top-4 left-4 z-50 rounded-[70px] overflow-hidden" style={{ width: '100px', height: '100px' }}>
          <Image
            src="/assets/bodybuilding-emblem-and-gym-logo-design-template-free-vector.jpg"
            alt="Gym Logo"
            width={100}
            height={100}
            className="w-full h-full object-cover"
          />
        </div>
        {children}
      </body>
    </html>
  );
}
